sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
addons:
  apt:
    packages:
      - graphviz
      - gdb
env:
  global:
    - CORE_BRANCH=master
    - APP_NAME=gallery
    - GH_REF: github.com/owncloud/gallery.git
    - secure: "cLmMqrbVZrvn2GAoVs6JWa5h70tzrAISjPZUfENjl0KYT6B84z3B94W/dGU+I2mxwvyBqEP+x83Bih2CxEflqc7tJmdqC+MM/ZZiigPX7RCjq5XHbzUpPpMbC8MFxT2K3jcFXUitfwZvNaZXJIiK3ZQJU4ayKaegLvI91x1SqH0="
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

cache:
  directories:
    # ${TRAVIS_BUILD_DIR} is /home/travis/build/owncloud/gallery/
    - ${TRAVIS_BUILD_DIR}/travis/php-cache
    - ${TRAVIS_BUILD_DIR}/travis/lib-cache
    - $HOME/.composer/cache

before_cache:
  # Archive the vendor folder. Watch closely!
  - cp -r ${TRAVIS_BUILD_DIR}/../core/apps/$APP_NAME/vendor ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum`

before_install:
  # Disable opcache on PHP 7.0 as it crashes too easily
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ]; then sed -i '/opcache.so/d' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;"
  - php --modules

  # Setup Selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - sh -c "if [ ! -e ${TRAVIS_BUILD_DIR}/travis/lib-cache/selenium.jar ]; then wget -O ${TRAVIS_BUILD_DIR}/travis/lib-cache/selenium.jar https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.0.jar; fi;"
  - java -jar ${TRAVIS_BUILD_DIR}/travis/lib-cache/selenium.jar -port 4444 >/dev/null 2>&1 & # WARNING - Takes a long time to start up. Keep here

  # Ghostdriver does not work on Travis - Download the latest PhantomJS
  #- mkdir travis-phantomjs
  #- sh -c "if [ ! -e ${TRAVIS_BUILD_DIR}/travis/lib-cache/phantomjs.tar.bz2 ]; then wget -O ${TRAVIS_BUILD_DIR}/travis/lib-cache/phantomjs.tar.bz2  https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2; fi;"
  #- tar -xvf ${TRAVIS_BUILD_DIR}/travis/lib-cache/phantomjs.tar.bz2
  #- export PATH=${TRAVIS_BUILD_DIR}/travis/lib-cache/phantomjs:$PATH
  #- phantomjs --webdriver=4444 --ignore-ssl-errors=true --webdriver-loglevel=DEBUG &

  # Get rid of Github limits
  # Only enable temporarily when making large package changes with composer
  #- git config --global github.accesstoken $GH_TOKEN

  # Make modifications to the environment to allow us to retrieve core dumps
  # When debugging, make sure you enable sudo by commenting out the first line of this file
  #- ulimit -c unlimited -S
  #- cat /proc/sys/kernel/core_pattern
  #- sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ]; then echo '/tmp/core_%e.%p' | sudo tee /proc/sys/kernel/core_pattern; fi;"
  #- cat /proc/sys/kernel/core_pattern

  # Installing ownCloud
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable $APP_NAME

before_script:
  # Make sure Webdriver is running
  - curl http://localhost:4444/wd/hub/status
  #- phantomjs --version

  # Install the Imagick PHP extension
  - sh -c "pecl config-set preferred_state beta; echo yes | printf "\n" | pecl install imagick;"

  # Disable xdebug when we don't need coverage to speed up testing
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' ]; then phpenv config-rm xdebug.ini; fi;"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' != 'mysql' ]; then phpenv config-rm xdebug.ini; fi;"
  # Always install the latest version of the xdebug PHP extension
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then cd build; bash xdebug_install.sh; cd ${TRAVIS_BUILD_DIR}/../core/apps/$APP_NAME; fi"

  # Sets up the PHP composer cache
  - sh -c "if [ ! -d ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum` ]; then mkdir -p ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum`; fi;"
  - rm -rf ${TRAVIS_BUILD_DIR}/../core/apps/$APP_NAME/vendor
  - sh -c "if [ -d ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum`/vendor ]; then cp -r ${TRAVIS_BUILD_DIR}/travis/php-cache/`php-config --vernum`/vendor ${TRAVIS_BUILD_DIR}/../core/apps/$APP_NAME; fi;"

  # Composer
  - cd ${TRAVIS_BUILD_DIR}/../core/apps/$APP_NAME
  - composer self-update
  - composer install -o --prefer-dist --no-interaction
  - composer show -i

script:
  # Test lint
  - php vendor/bin/parallel-lint --exclude travis --exclude vendor . vendor/composer vendor/symfony/yaml vendor/autoload.php

  # Acceptance tests, using Firefox, without code coverage
  - php vendor/bin/codecept run acceptance --env firefox
  # Unit, integration and api tests, without code coverage
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' ]; then php vendor/bin/codecept run api,integration,unit; fi;"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' != 'mysql' ]; then php vendor/bin/codecept run api,integration,unit; fi;"

  # PHP 5.6 ONLY: Unit, integration and api tests with code coverage
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then php vendor/bin/codecept run api,integration,unit --coverage --coverage-xml --coverage-html; fi;"
  # We can't use phpdbg only as it doesn't work with the webdriver and we can't use it for some tests only as we can't merge html reports
  # - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then phpenv config-rm xdebug.ini; phpdbg -qrr vendor/bin/codecept run api,integration,unit --coverage --coverage-xml --coverage-html; fi;"

after_success:
  # Send coverage report to Scrutinizer
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml; fi"

  # Generate API documentation
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then php vendor/bin/phpdoc run; fi"
  # Generate Wiki documentation
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then git submodule update --init; fi"
  # Send documentation to Github Pages
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '7.0' ] && [ '$DB' = 'mysql' ]; then cd build/documentation; bash ./docpublisher.sh; fi"

after_failure:
  - cat tests/_output/phpbuiltinserver.errors.txt
  - bash build/after_failure.sh

matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
    - php: 5.6
      env: DB=mysql
    - php: 7.0
      env: DB=mysql
  fast_finish: true
