language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7

branches:
  only:
    - master
    - dev
    - /^stable\d+(\.\d+)?$/

#before_install:
#  - cd ..
#  - git clone https://github.com/owncloud/core.git
#  - mv gallery core/apps/
#  - cd core
#  - git submodule init
#  - git submodule update
#  - cd apps/gallery

script: ant test
#  - phpunit tests
